spring:
  application:
    name: zc-hotel-web
  jackson:
    default-property-inclusion: non_null
    mapper:
      sort-properties-alphabetically: false
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://47.97.101.25:3306/hotel?useUnicode=true&characterEncoding=utf8
    username: root
    password: root123
server:
  port: 888
  context-path: /zc-hotel-web


mapper:
  mappers: com.dzsw.wqh.util.MyMapper
  not-empty: false
  identity: MYSQL
logging:
  level: info
