server:
  port : 888
spring:
  application:
    name: service-consume-movie
eureka:
  client:
    register-with-eureka: true #是否向服务注册中心注册自己
    fetch-registry: true #是否检索服务
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka #服务注册路径
      healthcheck:
        enabled: true
  instance:
    prefer-ip-address: true  #是否使用ip地址作为标识主机名
    #自定义配置主机名
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    #eureka客户端发送心跳所需的频率（以秒为单位） 默认为30秒一次
    lease-renewal-interval-in-seconds: 30
    #配置appname 则使spring.application.name 失效 注册eureka 上面的名称
    appname: movie-server
#配置文件 自定义ribbon策略
#service-provider-user:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


# 解决第一次请求报超时异常的方案：
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 1000
# 或者：
# hystrix.command.default.execution.timeout.enabled: false
# 或者：
#feign.hystrix.enabled: false ## 索性禁用feign的hystrix

# 超时的issue：https://github.com/spring-cloud/spring-cloud-netflix/issues/768
# 超时的解决方案： http://stackoverflow.com/questions/27375557/hystrix-command-fails-with-timed-out-and-no-fallback-available
# hystrix配置： https://github.com/Netflix/Hystrix/wiki/Configuration#execution.isolation.thread.timeoutInMilliseconds